#! /bin/bash

# Builds the YA3F bytecode and corresponding keccak hash 
# stores into ./script/utils/YAC3F.g.sol

OUTFILE="./script/utils/YAC3F.g.sol"

read -r -d '' PREFIX <<'EOF'
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

// Generated bytecode of the CREATE3 factory using `huffc -e paris -b`
bytes constant YAC3F_BYTECODE = hex"
EOF

printf "%s" "$PREFIX" > $OUTFILE

BYTECODE=$(huffc -e paris -b src/YAC3F.huff)

echo "$BYTECODE\";" >> $OUTFILE

echo "YAC3F bytecode:"
echo "$BYTECODE"
echo "Bytecode length: $(( ${#BYTECODE} / 2 ))"

CREATE_PROXY_BYTECODE=$(grep -m 1 -oP "CREATE_PROXY_BYTECODE\s*=\s*\K0x[[:xdigit:]]+" src/YAC3F.huff)

CREATE_PROXY_BYTECODE_HASH=$(cast k ${CREATE_PROXY_BYTECODE})

echo "" >> $OUTFILE
echo "// cast k $CREATE_PROXY_BYTECODE" >> $OUTFILE

echo "bytes32 constant CREATE_PROXY_BYTECODE_HASH = $CREATE_PROXY_BYTECODE_HASH;" >> $OUTFILE

echo "Generated $OUTFILE"
